In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd

In [7]:
path = "/content/post_feature_engineering.csv"
df = pd.read_csv(path)

In [8]:
df

,Unnamed: 0,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount_term,credit_history,property_area,loan_status,TotalIncome,TotalIncome_log,loan_amount_log
0,0,0,0,0,5849,0.0,360.0,1.0,2,1,5849.0,8.674026,4.852030
1,1,1,0,0,4583,1508.0,360.0,1.0,0,0,6091.0,8.714568,4.852030
2,2,0,0,1,3000,0.0,360.0,1.0,2,1,3000.0,8.006368,4.189655
3,3,0,1,0,2583,2358.0,360.0,1.0,2,1,4941.0,8.505323,4.787492
4,4,0,0,0,6000,0.0,360.0,1.0,2,1,6000.0,8.699515,4.948760
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,0,0,0,2900,0.0,360.0,1.0,0,1,2900.0,7.972466,4.262680
610,610,4,0,0,4106,0.0,180.0,1.0,0,1,4106.0,8.320205,3.688879
611,611,1,0,0,8072,240.0,360.0,1.0,2,1,8312.0,9.025456,5.533389
612,612,2,0,0,7583,0.0,360.0,1.0,2,1,7583.0,8.933664,5.231109
613,613,0,0,1,4583,0.0,360.0,0.0,1,0,4583.0,8.430109,4.890349

In [9]:
print(df.duplicated().sum())
# there is a duplicate so we drop it

0

In [10]:
df.drop_duplicates(inplace=True)

In [12]:
columns_to_drop = ['applicant_income', 'coapplicant_income', 'TotalIncome']
# Drop them using axis=1 (which means "columns")
df = df.drop(columns_to_drop, axis=1)

In [13]:
df

,Unnamed: 0,dependents,education,self_employed,loan_amount_term,credit_history,property_area,loan_status,TotalIncome_log,loan_amount_log
0,0,0,0,0,360.0,1.0,2,1,8.674026,4.852030
1,1,1,0,0,360.0,1.0,0,0,8.714568,4.852030
2,2,0,0,1,360.0,1.0,2,1,8.006368,4.189655
3,3,0,1,0,360.0,1.0,2,1,8.505323,4.787492
4,4,0,0,0,360.0,1.0,2,1,8.699515,4.948760
...,...,...,...,...,...,...,...,...,...,...
609,609,0,0,0,360.0,1.0,0,1,7.972466,4.262680
610,610,4,0,0,180.0,1.0,0,1,8.320205,3.688879
611,611,1,0,0,360.0,1.0,2,1,9.025456,5.533389
612,612,2,0,0,360.0,1.0,2,1,8.933664,5.231109
613,613,0,0,1,360.0,0.0,1,0,8.430109,4.890349

In [14]:
df.rename(columns={'TotalIncome_log': 'total_income_log'},inplace=True)
df

,Unnamed: 0,dependents,education,self_employed,loan_amount_term,credit_history,property_area,loan_status,total_income_log,loan_amount_log
0,0,0,0,0,360.0,1.0,2,1,8.674026,4.852030
1,1,1,0,0,360.0,1.0,0,0,8.714568,4.852030
2,2,0,0,1,360.0,1.0,2,1,8.006368,4.189655
3,3,0,1,0,360.0,1.0,2,1,8.505323,4.787492
4,4,0,0,0,360.0,1.0,2,1,8.699515,4.948760
...,...,...,...,...,...,...,...,...,...,...
609,609,0,0,0,360.0,1.0,0,1,7.972466,4.262680
610,610,4,0,0,180.0,1.0,0,1,8.320205,3.688879
611,611,1,0,0,360.0,1.0,2,1,9.025456,5.533389
612,612,2,0,0,360.0,1.0,2,1,8.933664,5.231109
613,613,0,0,1,360.0,0.0,1,0,8.430109,4.890349

In [20]:
df.to_csv('ML_ready.csv', index=False)